### ISSUE TITLE
Postman giving me an error when checking auth/verify route

### ISSUE THREAD

**Issue by kingram6865** [kingram6865/job-search-tracker#1]
User Info: 
```
{
    "user": {
        "id": 1,
        "username": "mary",
        "email": "ken.ingram@gmail.com",
        "created_at": "2020-10-20T02:58:24.965Z",
        "updated_at": "2020-10-20T02:58:24.965Z"
    },
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAzMjU0NjgwfQ.IcRg-DdvoB4rhj0z7O7a-8epBAXajKZsKW4g3PYL8gA"
}
```

Postman URI:
`http://192.168.1.19:3000/auth/verify?Authorization="Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAzMjU0NjgwfQ.IcRg-DdvoB4rhj0z7O7a-8epBAXajKZsKW4g3PYL8gA"`

```
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `message' for nil:NilClass>",
    "traces": {
        "Application Trace": [
            {
                "exception_object_id": 21180,
                "id": 0,
                "trace": "app/controllers/application_controller.rb:23:in `rescue in authorize_request'"
            },
            {
                "exception_object_id": 21180,
                "id": 1,
                "trace": "app/controllers/application_controller.rb:17:in `authorize_request'"
            }
        ],
        "Framework Trace": [
            {
                "exception_object_id": 21180,
                "id": 2,
                "trace": "activesupport (6.0.3.4) lib/active_support/callbacks.rb:428:in `block in make_lambda'"
            },

```
ETC... (Long stack of exceptions)

**Comment by kingram6865** [comment]
In `authentication_controller.rb` 

Line 6:     `@user = User.find_by_username(login_params[:username])`
should be:  `@user = User.find_by(username: login_params[:username])`

In `application_controller.rb`
Line 19:  `@current_user = User.find(@decoded[:user_id])`
should be:  `@current_user = User.find(@decoded[:id])`
