### ISSUE TITLE
auth/verify is throwing a 500 error

### ISSUE THREAD

**Issue by kingram6865** [kingram6865/job-search-tracker#3]
It was working previously, now broken.

```
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `message' for nil:NilClass>",
    "traces": {
        "Application Trace": [
            {
                "exception_object_id": 35800,
                "id": 0,
                "trace": "app/controllers/application_controller.rb:25:in `rescue in authorize_request'"
            },
            {
                "exception_object_id": 35800,
                "id": 1,
                "trace": "app/controllers/application_controller.rb:17:in `authorize_request'"
            }
        ],
```

**Comment by kingram6865** [comment]
Mick helped resolve this one.
Unneeded code written into authorize_request.
Once removed code functioned.

Also, misnamed inputs in the Edit component for companies.
